# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markov_functions', '0002_auto_20170720_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Site Books'},
        ),
    ]
