# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markov_functions.models


class Migration(migrations.Migration):

    dependencies = [
        ('markov_functions', '0003_auto_20170723_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to=markov_functions.models.get_book_directory_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
