# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markov_functions', '0004_auto_20170829_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lines',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
