# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import markov_functions.models


class Migration(migrations.Migration):

    dependencies = [
        ('markov_functions', '0006_book_sentences'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='model',
            field=models.FileField(blank=True, upload_to=markov_functions.models.get_book_directory_path),
        ),
    ]
