# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markov_functions', '0007_book_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
